version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      root-compatible-updates:
        patterns: ["*"]
  - package-ecosystem: "cargo"
    directory: "/fuzz"
    schedule:
      interval: "weekly"
    groups:
      fuzz-compatible-updates:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
