[package]
name = "encryptor"
autobins = false
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.9"
anyhow = "1.0"
argon2 = "0.5"
zeroize = "1.5"
sha2 = "0.10"
hex = "0.4"
poly1305 = "0.8.0"
libc = "0.2"
secrecy = "0.8"

[dev-dependencies]
proptest = "1.0"
tempfile = "3.5"
autocfg = "1.4.0"

[[bin]]
name = "chacha20_poly1305"
path = "src/main.rs"
