[package]
name = "encryptor-fuzz"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
afl = "0.16"

[dependencies.encryptor]
path = ".."
version = "0.53.0"

[features]
afl = []

[[bin]]
name = "header_afl"
path = "fuzz_targets/header_afl.rs"
required-features = ["afl"]

[[bin]]
name = "structure_afl"
path = "fuzz_targets/structure_afl.rs"
required-features = ["afl"]
