name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            vendor
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install security tools
        run: |
          cargo install --version ^0.17 cargo-audit
          cargo install --version ^0.11 cargo-deny
          cargo install --version ^0.2 cargo-auditable
      - name: Run checks
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo test --offline
          cargo audit --locked --deny warnings
          cargo deny check
