name: Verification

on:
  pull_request:
  workflow_dispatch:

jobs:
  prusti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Prusti verifier
        uses: viperproject/prusti-action@v1
        with:
          path: "."             # your crate root (where Cargo.toml lives)
          version: "nightly"    # pick the nightly toolchain Prusti needs
          verify-crate: true    # run full crate verification

