name: Verification

on:
  pull_request:
  workflow_dispatch:

jobs:
  prusti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pin base64ct for Prusti
        run: cargo update -p base64ct --precise 1.7.2
      - name: Downgrade Cargo.lock to v3 for Prusti
        run: |
          # On Linux/GitHub Actions Ubuntu:
          sed -i 's/^version = 4$/version = 3/' Cargo.lock
          git diff Cargo.lock

      - name: Run Prusti verifier
        uses: viperproject/prusti-action@v1
        with:
          path: "."             # your crate root (where Cargo.toml lives)
          version: "nightly"    # pick the nightly toolchain Prusti needs
          verify-crate: true    # run full crate verification

